version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing Dependancies
          command: apt-get update && apt-get install yasm binutils make
      - run:
          name: Making Alpha.bin
          command: make Alpha.bin
