version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing Dependancies
          command: sudo apt install yasm ld
      - run:
          name: Making Alpha.bin
          command: make Alpha.bin